<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            ['code' => 'SP01', 'name' => 'SUSIANTO', 'address' => 'SAWAHAN', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 6302518938.91, 'is_active' => false],
            ['code' => 'SP02', 'name' => 'CINDY', 'address' => 'JAKARTA', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 20842115941.2, 'is_active' => true],
            ['code' => 'SP03', 'name' => 'MOCH HASAN', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 148719154.75, 'is_active' => false],
            ['code' => 'SP04', 'name' => 'TEGAL INDUSTRI', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 35136455, 'is_active' => false],
            ['code' => 'SP05', 'name' => 'SUTRIS', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 87627750, 'is_active' => false],
            ['code' => 'SP06', 'name' => 'UD. BERDIKARI', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'SP07', 'name' => 'UD. ELIM', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'SP08', 'name' => 'IDA TAJIMA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 28406072718.39, 'is_active' => false],
            ['code' => 'SP09', 'name' => 'TIMBANGAN MAKMUR', 'address' => 'JKT', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 119411950, 'is_active' => false],
            ['code' => '08', 'name' => 'CE LIDYA', 'address' => 'JKT', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 23587541, 'is_active' => false],
            ['code' => 'SP10', 'name' => 'TUNGKI', 'address' => 'JKT', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 88936200, 'is_active' => false],
            ['code' => 'SP11', 'name' => 'YOHAN', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 1725404761.41, 'is_active' => false],
            ['code' => 'S12', 'name' => 'ANWAR', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 2597835284.24, 'is_active' => false],
            ['code' => 'S13', 'name' => 'TONI LUKMAN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 11913110, 'is_active' => false],
            ['code' => 'S14', 'name' => 'PAK SUKUR', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 213525000, 'is_active' => false],
            ['code' => 'S15', 'name' => 'ANTON FITIYADI', 'address' => 'SWETA', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 130708382.04, 'is_active' => false],
            ['code' => 'S16', 'name' => 'UD. ABADI', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 36467685.75, 'is_active' => false],
            ['code' => 'S17', 'name' => 'SWIE LIANG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 2211985288.78, 'is_active' => false],
            ['code' => 'S18', 'name' => 'ADI MENSANA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 68674916.8, 'is_active' => false],
            ['code' => 'S19', 'name' => 'YENITIO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 10402000, 'is_active' => false],
            ['code' => 'S20', 'name' => 'AKIAT', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 558068320, 'is_active' => false],
            ['code' => 'S21', 'name' => 'MOCH NADIR', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 195886185.28, 'is_active' => false],
            ['code' => 'S22', 'name' => 'MUKSON', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 1017195950, 'is_active' => false],
            ['code' => 'S23', 'name' => 'DIMAS', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 901109350.92, 'is_active' => false],
            ['code' => 'S24', 'name' => 'NIAGA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S25', 'name' => 'SAE LESTARI', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 74600500, 'is_active' => false],
            ['code' => 'S26', 'name' => 'HERNANDES', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 29191000, 'is_active' => false],
            ['code' => 'S27', 'name' => 'SEMERU', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 504043871.46, 'is_active' => false],
            ['code' => 'S28', 'name' => 'ARTUPIC', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 148614420, 'is_active' => false],
            ['code' => 'S29', 'name' => 'ONLINE SHOP', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 565062203.13, 'is_active' => false],
            ['code' => 'S30', 'name' => 'SUGIANTO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 140067222.44, 'is_active' => false],
            ['code' => 'S31', 'name' => 'ROSIDI', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 705060077.7, 'is_active' => false],
            ['code' => 'S32', 'name' => 'SUGIARTO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 18677128, 'is_active' => false],
            ['code' => 'S34', 'name' => 'SANTOSO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 8202000, 'is_active' => false],
            ['code' => 'S33', 'name' => 'BINTORO RAHARJO IWAN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 183507148.9, 'is_active' => false],
            ['code' => 'S35', 'name' => 'LINA', 'address' => 'JAKARTA', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 163278611.1, 'is_active' => false],
            ['code' => 'S37', 'name' => 'MUJUR MAS', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 18290500, 'is_active' => false],
            ['code' => 'S38', 'name' => 'SARAH', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 4440000, 'is_active' => false],
            ['code' => 'S040', 'name' => 'FRANKY WIJAYA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S40', 'name' => 'KOKOH', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 75915901.5, 'is_active' => false],
            ['code' => 'S45', 'name' => 'MERAKI CHEMINDO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 72695000, 'is_active' => false],
            ['code' => 'S46', 'name' => 'BINTORO RAHARJO IWAN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 15230000, 'is_active' => false],
            ['code' => 'S47', 'name' => 'GEDE', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 510000, 'is_active' => false],
            ['code' => 'S49', 'name' => 'ROBY BANGUNAN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 10700000, 'is_active' => false],
            ['code' => 'S50', 'name' => 'YUDI HARIANTO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 71783000, 'is_active' => false],
            ['code' => 'S51', 'name' => 'AZIZ DARMAWAN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 132318257.5, 'is_active' => false],
            ['code' => 'S52', 'name' => 'RJ STEEL', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S56', 'name' => 'JANGKAR MAS', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 3445000, 'is_active' => false],
            ['code' => 'S55', 'name' => 'CV. ASTRACO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 8005350, 'is_active' => false],
            ['code' => 'S59', 'name' => 'SINAR AGUNG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 40728014.17, 'is_active' => false],
            ['code' => 'S60', 'name' => 'AVIPEN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 277975500, 'is_active' => false],
            ['code' => 'S58', 'name' => 'RUCIKA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 769337764.65, 'is_active' => false],
            ['code' => 'S70', 'name' => 'HC', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 29972000, 'is_active' => false],
            ['code' => 'S67', 'name' => 'NUSANTARA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 2527331370.91, 'is_active' => false],
            ['code' => 'S78', 'name' => 'LOTUS', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 279378736.52, 'is_active' => false],
            ['code' => 'S77', 'name' => 'WONGSO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 7200000, 'is_active' => false],
            ['code' => 'S89', 'name' => 'BELI RETUR', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 94809999.8, 'is_active' => false],
            ['code' => 'S90', 'name' => 'BESI SEGANTENG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 22934960, 'is_active' => false],
            ['code' => 'S91', 'name' => 'GUNUNG KIJANG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 3900000, 'is_active' => false],
            ['code' => 'S92', 'name' => 'ROBY LUKITO', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 21805200, 'is_active' => false],
            ['code' => 'S96', 'name' => 'JUMAIN', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S93', 'name' => 'PT MUSTIKA RAYA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S94', 'name' => 'YANAPRIMA HASTAPERSADA', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 31641682, 'is_active' => false],
            ['code' => 'S100', 'name' => 'JEMY CHANDRA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 173523000, 'is_active' => false],
            ['code' => 'S101', 'name' => 'AWIM MEDION', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 3087500, 'is_active' => false],
            ['code' => 'S122', 'name' => 'PT. BANGUN INDOPRALON SUKSES', 'address' => 'BANYUMULEK', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 190386380, 'is_active' => false],
            ['code' => 'S123', 'name' => 'ALUNG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S127', 'name' => 'ARCO LISTRIK', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 1942000, 'is_active' => false],
            ['code' => 'S129', 'name' => 'SUMBER DJAJA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 40346219.8, 'is_active' => false],
            ['code' => 'S130', 'name' => 'HOME INDONESIA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S132', 'name' => 'BANGUN INDOPRALON SUKSES', 'address' => 'banyumulek', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 116267765, 'is_active' => false],
            ['code' => 'S137', 'name' => 'DIDIK SUPIR', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S150', 'name' => 'RONI DWINARTO', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S200', 'name' => 'AF TIMBANGAN', 'address' => 'surabaya', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S201', 'name' => 'AGRINUSA', 'address' => 'ampenan', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 16468000, 'is_active' => false],
            ['code' => 'S230', 'name' => 'TUBAGUS', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 198260660.5, 'is_active' => false],
            ['code' => 'S233', 'name' => 'DAYAT', 'address' => 'kediri', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 5175000, 'is_active' => false],
            ['code' => 'S238', 'name' => 'IQBAL', 'address' => 'BTN GRIYA PESONA ALAM', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 56450000, 'is_active' => false],
            ['code' => 'S251', 'name' => 'CV. DEKATEX', 'address' => 'SURABAYA', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 24310000, 'is_active' => false],
            ['code' => 'S256', 'name' => 'VEROS', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 790839000, 'is_active' => false],
            ['code' => 'S246', 'name' => 'CV. JAYA BERSAMA PUTRA PERKASA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 17320400, 'is_active' => false],
            ['code' => 'S300', 'name' => 'CV BANDUNG', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S301', 'name' => 'RICHARD', 'address' => 'apmpenan', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 25149375, 'is_active' => false],
            ['code' => 'S007', 'name' => 'TOKO BAMA', 'address' => '', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
            ['code' => 'S236', 'name' => 'SINAR JAYA', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 127892000, 'is_active' => false],
            ['code' => 'S345', 'name' => 'BUDI', 'address' => 'SBY', 'phone' => '', 'email' => '', 'npwp' => '', 'contact_person' => '', 'opening_balance' => 0, 'current_balance' => 0, 'is_active' => false],
        ];

        foreach ($suppliers as $data) {
            Supplier::firstOrCreate(['code' => $data['code']], $data);
        }
    }
}
